confluent:
  control:
    center:
      user: cp-control-center
      group: confluent
      config_file: /etc/confluent-control-center/control-center-production.properties
      service_name: confluent-control-center
      config:
        confluent.controlcenter.streams.num.stream.threads: 8
        confluent.controlcenter.data.dir: /var/lib/confluent/control-center
      systemd:
        enabled: yes
        state: started
