ksql:
  config_file: /etc/ksql/ksql-server.properties
  service_name: confluent-ksql
  user: cp-ksql
  group: confluent
  config:
    application.id: ksql-server
    listeners: http://localhost:8088
  systemd:
    enabled: yes
    state: started
